In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

In [2]:
df = pd.read_csv('/content/drive/MyDrive/CV Data Life Expectancy Data (1) (2).csv')
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Country                          2938 non-null   object 
 1   Year                             2938 non-null   int64  
 2   Status                           2938 non-null   object 
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64  
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64  
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64  
 12  Polio               

In [4]:
df['Country'].nunique()

193

In [5]:
df['Status'].value_counts()

,count
Status,
Developing,2426
Developed,512


In [6]:
df['Developing_Status'] = np.where(df['Status'] == 'Developing', 1, 0)


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Country                          2938 non-null   object 
 1   Year                             2938 non-null   int64  
 2   Status                           2938 non-null   object 
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64  
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64  
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64  
 12  Polio               

In [8]:
df.isnull().sum()

,0
Country,0
Year,0
Status,0
Life expectancy,10
Adult Mortality,10
infant deaths,0
Alcohol,194
percentage expenditure,0
Hepatitis B,553
Measles,0


In [9]:
le = LabelEncoder()
df['Country_encoded'] = le.fit_transform(df['Country'])

df = df.drop(['Country'], axis=1)

In [10]:
df.columns

Index(['Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Developing_Status',
       'Country_encoded'],
      dtype='object')

In [11]:
df.shape


(2938, 23)

In [12]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Developing_Status,Country_encoded
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,...,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000,2938.000000,2938.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,...,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793,0.825732,95.096324
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,...,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920,0.379405,56.244904
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,...,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,...,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000,1.000000,46.000000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,...,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,1.000000,93.000000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,...,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000,1.000000,145.000000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,...,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,1.000000,192.000000


In [13]:
df.isnull().sum()

,0
Year,0
Status,0
Life expectancy,10
Adult Mortality,10
infant deaths,0
Alcohol,194
percentage expenditure,0
Hepatitis B,553
Measles,0
BMI,34


In [14]:
df['Life expectancy '].fillna(df['Life expectancy '].median(), inplace=True)
df['Adult Mortality'].fillna(df['Adult Mortality'].median(), inplace=True)
df['Hepatitis B'].fillna(df['Hepatitis B'].median(), inplace=True)
df['Measles '].fillna(df['Measles '].median(), inplace=True)
df[' BMI '].fillna(df[' BMI '].median(), inplace=True)
df['under-five deaths '].fillna(df['under-five deaths '].median(), inplace=True)
df[' HIV/AIDS'].fillna(df[' HIV/AIDS'].median(), inplace=True)
df['Total expenditure'].fillna(df['Total expenditure'].median(), inplace=True)
df['GDP'].fillna(df['GDP'].median(), inplace=True)
df['Population'].fillna(df['Population'].median(), inplace=True)
df[' thinness  1-19 years'].fillna(df[' thinness  1-19 years'].median(), inplace=True)
df[' thinness 5-9 years'].fillna(df[' thinness 5-9 years'].median(), inplace=True)
df['Income composition of resources'].fillna(df['Income composition of resources'].median(), inplace=True)
df['Schooling'].fillna(df['Schooling'].median(), inplace=True)
df['Alcohol'].fillna(df['Alcohol'].median(), inplace=True)
df['Polio'].fillna(df['Polio'].median(), inplace=True)
df['Diphtheria '].fillna(df['Diphtheria '].median(), inplace=True)

/tmp/ipykernel_4750/3805525009.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Life expectancy '].fillna(df['Life expectancy '].median(), inplace=True)
/tmp/ipykernel_4750/3805525009.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method

In [15]:
df.isnull().sum()

,0
Year,0
Status,0
Life expectancy,0
Adult Mortality,0
infant deaths,0
Alcohol,0
percentage expenditure,0
Hepatitis B,0
Measles,0
BMI,0


In [16]:
x = df.drop(['Life expectancy ','Status'],axis=1)
y = df['Life expectancy ']

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
model.coef_

array([ 1.77063793e-04, -2.07644350e-02,  9.81486326e-02,  6.16734117e-02,
        5.47380733e-05, -1.97409863e-02, -2.28083264e-05,  4.05189955e-02,
       -7.29922151e-02,  2.73996533e-02,  3.23984005e-02,  4.15221714e-02,
       -4.63106023e-01,  3.86635522e-05, -1.14526806e-09, -9.50868212e-02,
        1.22882381e-02,  6.13420194e+00,  6.38808998e-01, -1.62114657e+00,
        3.11149451e-03])

In [20]:

train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [21]:
train_pred[:5]

array([69.88245046, 64.23117831, 73.01239076, 76.88514842, 73.20494989])

In [22]:
y_train.values[:5]

array([72.3, 73. , 74.6, 74.9, 74.8])

In [23]:
test_pred[:5]

array([67.35754062, 77.09377993, 75.74295374, 77.81406135, 46.80560764])

In [24]:
y_test.values[:5]

array([73.7, 75.9, 74.2, 76.8, 51.9])

In [25]:
print('Train  mean_squared_error :-',mean_squared_error(y_train,train_pred))
print('Train  mean_absolute_error :-',mean_absolute_error(y_train,train_pred))
print('Train  mean_absolute_percentage_error :-',mean_absolute_percentage_error(y_train,train_pred)*100)

Train  mean_squared_error :- 16.55017830122056
Train  mean_absolute_error :- 3.0359557088951883
Train  mean_absolute_percentage_error :- 4.646543944889795


In [26]:
print('Test mean_squared_error :-', mean_squared_error(y_test, test_pred))
print('Test mean_absolute_error :-', mean_absolute_error(y_test, test_pred))
print('Test mean_absolute_percentage_error :-', mean_absolute_percentage_error(y_test, test_pred)*100)

Test mean_squared_error :- 15.140179250257937
Test mean_absolute_error :- 2.8457665309713422
Test mean_absolute_percentage_error :- 4.378584380507724


In [27]:
import joblib
import os

In [28]:
joblib.dump(
    model,
    "linear_regression_model.pkl"
)


['linear_regression_model.pkl']

In [29]:
joblib.dump(
    model,
    "country_encoder.pkl"
)


['country_encoder.pkl']

In [30]:
joblib.dump(
    model,
    "feature_column.pkl"
)


['feature_column.pkl']

In [32]:
import joblib

# Verify pehle
print("le ka type:", type(le))
print("le ke paas classes_ hai:", hasattr(le, 'classes_'))

# Ab save karo
joblib.dump(le, "MYFIX_country_encoder.pkl")

# Turant verify karo
check = joblib.load("MYFIX_country_encoder.pkl")
print("Saved file ka type:", type(check))
print("Classes:", check.classes_[:5])

from google.colab import files
files.download("MYFIX_country_encoder.pkl")

le ka type: <class 'sklearn.preprocessing._label.LabelEncoder'>
le ke paas classes_ hai: True
Saved file ka type: <class 'sklearn.preprocessing._label.LabelEncoder'>
Classes: ['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Antigua and Barbuda']


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>